### ISSUE TITLE
Compatible with Material-ui Dialog component ?

### ISSUE THREAD

**Issue by jy95** [jcoreio/material-ui-popup-state#53]
Hello,

I wonder if your package is compatible with Material-ui [Dialog](https://material-ui.com/components/dialogs/#dialog) component ?

I tested with `bindContextMenu` and `bindPopper` and I got the following warning : 
```js
Warning: React does not recognize the `anchorEl` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `anchorel` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at div
    at Portal (http://localhost:3000/yt_gaming_library/static/js/vendors~main.chunk.js:21031:24)
    at Modal (http://localhost:3000/yt_gaming_library/static/js/vendors~main.chunk.js:18183:83)
    at Dialog (http://localhost:3000/yt_gaming_library/static/js/vendors~main.chunk.js:7695:29)
    at WithStyles(ForwardRef(Dialog)) (http://localhost:3000/yt_gaming_library/static/js/vendors~main.chunk.js:52648:31)
    at CardDialog (http://localhost:3000/yt_gaming_library/static/js/main.chunk.js:790:75)
    at div
    at Paper (http://localhost:3000/yt_gaming_library/static/js/vendors~main.chunk.js:19945:23)
    at WithStyles(ForwardRef(Paper)) (http://localhost:3000/yt_gaming_library/static/js/vendors~main.chunk.js:52648:31)
    at Card (http://localhost:3000/yt_gaming_library/static/js/vendors~main.chunk.js:4801:23)
    at WithStyles(ForwardRef(Card)) (http://localhost:3000/yt_gaming_library/static/js/vendors~main.chunk.js:52648:31)
    at CardEntry (http://localhost:3000/yt_gaming_library/static/js/main.chunk.js:1131:90)
    at div
    at Grid (http://localhost:3000/yt_gaming_library/static/js/vendors~main.chunk.js:11900:35)
    at WithStyles(ForwardRef(Grid)) (http://localhost:3000/yt_gaming_library/static/js/vendors~main.chunk.js:52648:31)
    at div
    at Grid (http://localhost:3000/yt_gaming_library/static/js/vendors~main.chunk.js:11900:35)
    at WithStyles(ForwardRef(Grid)) (http://localhost:3000/yt_gaming_library/static/js/vendors~main.chunk.js:52648:31)
    at GamesGallery (http://localhost:3000/yt_gaming_library/static/js/main.chunk.js:1397:5)
    at Connect(GamesGallery) (http://localhost:3000/yt_gaming_library/static/js/vendors~main.chunk.js:103314:75)
    at Route (http://localhost:3000/yt_gaming_library/static/js/vendors~main.chunk.js:106219:29)
    at div
    at Grid (http://localhost:3000/yt_gaming_library/static/js/vendors~main.chunk.js:11900:35)
    at WithStyles(ForwardRef(Grid)) (http://localhost:3000/yt_gaming_library/static/js/vendors~main.chunk.js:52648:31)
    at main
    at Router (http://localhost:3000/yt_gaming_library/static/js/vendors~main.chunk.js:105854:30)
    at BrowserRouter (http://localhost:3000/yt_gaming_library/static/js/vendors~main.chunk.js:105474:35)
    at Provider (http://localhost:3000/yt_gaming_library/static/js/vendors~main.chunk.js:103027:20)
    at div
    at ThemeProvider (http://localhost:3000/yt_gaming_library/static/js/vendors~main.chunk.js:51350:24)
    at Root (http://localhost:3000/yt_gaming_library/static/js/main.chunk.js:4756:80)
    at Connect(Root) (http://localhost:3000/yt_gaming_library/static/js/vendors~main.chunk.js:103314:75)
    at I18nextProvider (http://localhost:3000/yt_gaming_library/static/js/vendors~main.chunk.js:98533:19)
```

As Dialog requires open attribute (but not anchorEl), I have to use a ugly workaround to not have this error : 

```js
// workaround as React doesn't support anchorEl for Dialog
const {anchorEl: _notNeeded, ...dialogProps} = bindPopper(popupState);

<Dialog
            aria-labelledby="game-context-dialog-title"
            {...dialogProps}
>

</Dialog>
```

Thanks in advance

**Comment by jedwards1211** [comment]
Nah, I'm afraid it's not.  There's not much justification for using any special state management for Dialogs because the only property you need to manage is `open`.  With popups and popovers you have to manage more properties like `anchorEl` and aria props linking the popup to the trigger, which was the main reason I created this library.
